# Generated by Django 5.2.15 on 2026-06-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='student_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
