# Generated by Django 5.2.15 on 2026-06-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveSmallIntegerField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('counted_hours', models.PositiveSmallIntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='attendance.classsession')),
            ],
            options={
                'ordering': ('section_number',),
            },
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(fields=('course', 'date'), name='unique_course_session_date'),
        ),
        migrations.AddConstraint(
            model_name='sessionsection',
            constraint=models.UniqueConstraint(fields=('session', 'section_number'), name='unique_session_section_number'),
        ),
        migrations.AddConstraint(
            model_name='sessionsection',
            constraint=models.CheckConstraint(condition=models.Q(('section_number__gte', 1), ('section_number__lte', 3)), name='valid_session_section_number'),
        ),
        migrations.AddConstraint(
            model_name='sessionsection',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes', 45)), name='session_section_duration_is_45'),
        ),
        migrations.AddConstraint(
            model_name='sessionsection',
            constraint=models.CheckConstraint(condition=models.Q(('counted_hours', 1)), name='session_section_counted_hours_is_1'),
        ),
    ]
