# Generated by Django 5.2.15 on 2026-06-04 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave')], max_length=10)),
                ('recorded_method', models.CharField(choices=[('MANUAL', 'Manual'), ('QR', 'QR'), ('SYSTEM', 'System')], default='MANUAL', max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.course')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.sessionsection')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.classsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-recorded_at',),
                'constraints': [models.UniqueConstraint(fields=('student', 'section'), name='unique_student_section_attendance'), models.CheckConstraint(condition=models.Q(('status__in', ['PRESENT', 'LATE', 'ABSENT', 'LEAVE'])), name='valid_attendance_status'), models.CheckConstraint(condition=models.Q(('recorded_method__in', ['MANUAL', 'QR', 'SYSTEM'])), name='valid_attendance_recorded_method')],
            },
        ),
    ]
